-- Q1. What is the total revenue generated by male vs. female customers?
/*
SELECT gender,SUM(purchase_amount) AS revenue
FROM `dotted-music-443114-f2.customer_analysis.customer_behavior`
GROUP BY gender;
*/

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
/*
SELECT customer_id, purchase_amount
FROM `dotted-music-443114-f2.customer_analysis.customer_behavior`
WHERE  discount_applied = 'Yes' 
AND  purchase_amount >= 
    (SELECT AVG(purchase_amount) AS avg_purchase_amount
     FROM `dotted-music-443114-f2.customer_analysis.customer_behavior`);
*/

-- Q3. Which are the top 5 products with the highest average review rating?
/*
SELECT item_purchased, ROUND(AVG(review_rating),2) AS avg_product_rating
FROM `dotted-music-443114-f2.customer_analysis.customer_behavior`
GROUP BY item_purchased
ORDER BY avg_product_rating DESC
LIMIT 5;
*/

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
/*
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
FROM `dotted-music-443114-f2.customer_analysis.customer_behavior`
WHERE shipping_type = 'Standard'
OR  shipping_type = 'Express'
GROUP BY shipping_type
ORDER BY avg_purchase_amount DESC
*/

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
/*
SELECT subscription_status, 
       COUNT(customer_id) AS total_customers, 
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue

FROM `dotted-music-443114-f2.customer_analysis.customer_behavior`
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC
*/

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
/*
SELECT item_purchased, 
       ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN  1 ELSE 0 END)
       /COUNT(*),2) AS discount_rate 
FROM `dotted-music-443114-f2.customer_analysis.customer_behavior`
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
*/

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
/*
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM `dotted-music-443114-f2.customer_analysis.customer_behavior`
)
SELECT customer_segment, COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment
*/

-- Q8. What are the top 3 most purchased products within each category?
/*
WITH item_counts AS (
  SELECT category, item_purchased,
  COUNT(customer_id) AS total_orders,
  ROW_NUMBER () OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
  FROM `dotted-music-443114-f2.customer_analysis.customer_behavior`
  GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;
*/

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
/*
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM `dotted-music-443114-f2.customer_analysis.customer_behavior`
WHERE previous_purchases > 5
GROUP BY subscription_status
*/

-- Q10. What is the revenue contribution of each age group?
/*
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM `dotted-music-443114-f2.customer_analysis.customer_behavior`
GROUP BY  age_group
ORDER BY total_revenue DESC;
*/

-- Q11. For each combination of category and size, what is the average purchase_amount and total revenue, and which 3 combinations generate the highest total revenue overall?
/*
SELECT ROUND(AVG(purchase_amount),2) AS avg_purchase_amount,
       SUM(purchase_amount) AS total_revenue,
       category,
       size
FROM `dotted-music-443114-f2.customer_analysis.customer_behavior`
GROUP BY category, size
ORDER BY total_revenue DESC
LIMIT 3;
*/

-- Q12. By location, what are the total revenue and average revenue per customer, and which locations have the highest revenue per customer?
/*
WITH customer_location_revenue AS(
       SELECT customer_id,
              location,
              SUM(purchase_amount) AS customer_revenue
       FROM `dotted-music-443114-f2.customer_analysis.customer_behavior`
       GROUP BY customer_id, location
)

SELECT location,
       COUNT(DISTINCT customer_id) AS unique_customers,
       SUM(customer_revenue) AS total_revenue,
       ROUND(AVG(customer_revenue),2) AS avg_revenue_per_customer
FROM customer_location_revenue
GROUP BY location
ORDER BY avg_revenue_per_customer DESC;
*/
